// Types
export interface TopicItem {
  name: string;
  questionCount: number;
  enabled: boolean;
}

export interface MachineQuestionItem {
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

// Common roles for interview creation
export const INTERVIEW_ROLES = [
  { value: 'SDE-1', label: 'Software Development Engineer - 1' },
  { value: 'SDE-2', label: 'Software Development Engineer - 2' },
  { value: 'SDE-3', label: 'Software Development Engineer - 3' },
  { value: 'Senior Software Engineer', label: 'Senior Software Engineer' },
  { value: 'Staff Software Engineer', label: 'Staff Software Engineer' },
  { value: 'Principal Software Engineer', label: 'Principal Software Engineer' },
  { value: 'Frontend Developer', label: 'Frontend Developer' },
  { value: 'Backend Developer', label: 'Backend Developer' },
  { value: 'Full Stack Developer', label: 'Full Stack Developer' },
  { value: 'DevOps Engineer', label: 'DevOps Engineer' },
  { value: 'Site Reliability Engineer', label: 'Site Reliability Engineer' },
  { value: 'Data Engineer', label: 'Data Engineer' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'ML Engineer', label: 'Machine Learning Engineer' },
  { value: 'AI Engineer', label: 'AI Engineer' },
  { value: 'Mobile Developer', label: 'Mobile Developer' },
  { value: 'iOS Developer', label: 'iOS Developer' },
  { value: 'Android Developer', label: 'Android Developer' },
  { value: 'React Native Developer', label: 'React Native Developer' },
  { value: 'Flutter Developer', label: 'Flutter Developer' },
  { value: 'Game Developer', label: 'Game Developer' },
  { value: 'Unity Developer', label: 'Unity Developer' },
  { value: 'Unreal Engine Developer', label: 'Unreal Engine Developer' },
  { value: 'Blockchain Developer', label: 'Blockchain Developer' },
  { value: 'Web3 Developer', label: 'Web3 Developer' },
  { value: 'Security Engineer', label: 'Security Engineer' },
  { value: 'Cloud Engineer', label: 'Cloud Engineer' },
  { value: 'Solutions Architect', label: 'Solutions Architect' },
  { value: 'Technical Lead', label: 'Technical Lead' },
  { value: 'Engineering Manager', label: 'Engineering Manager' },
  { value: 'Product Manager', label: 'Product Manager' },
  { value: 'Technical Product Manager', label: 'Technical Product Manager' },
  { value: 'QA Engineer', label: 'QA Engineer' },
  { value: 'Test Automation Engineer', label: 'Test Automation Engineer' },
  { value: 'Performance Engineer', label: 'Performance Engineer' },
  { value: 'Database Administrator', label: 'Database Administrator' },
  { value: 'System Administrator', label: 'System Administrator' },
  { value: 'Network Engineer', label: 'Network Engineer' },
  { value: 'Cybersecurity Analyst', label: 'Cybersecurity Analyst' },
  { value: 'Penetration Tester', label: 'Penetration Tester' },
  { value: 'UI/UX Designer', label: 'UI/UX Designer' },
  { value: 'Product Designer', label: 'Product Designer' },
  { value: 'UX Researcher', label: 'UX Researcher' },
  { value: 'Technical Writer', label: 'Technical Writer' },
  { value: 'Developer Advocate', label: 'Developer Advocate' },
  { value: 'Solutions Engineer', label: 'Solutions Engineer' },
  { value: 'Sales Engineer', label: 'Sales Engineer' },
];

// Common tech stacks and technologies for interview questions
export const TECH_STACKS = [
  // Frontend Technologies
  { value: 'React', label: 'React', category: 'Frontend' },
  { value: 'Vue.js', label: 'Vue.js', category: 'Frontend' },
  { value: 'Angular', label: 'Angular', category: 'Frontend' },
  { value: 'Svelte', label: 'Svelte', category: 'Frontend' },
  { value: 'Next.js', label: 'Next.js', category: 'Frontend' },
  { value: 'Nuxt.js', label: 'Nuxt.js', category: 'Frontend' },
  { value: 'Gatsby', label: 'Gatsby', category: 'Frontend' },
  { value: 'JavaScript', label: 'JavaScript', category: 'Frontend' },
  { value: 'TypeScript', label: 'TypeScript', category: 'Frontend' },
  { value: 'HTML', label: 'HTML', category: 'Frontend' },
  { value: 'CSS', label: 'CSS', category: 'Frontend' },
  { value: 'SCSS', label: 'SCSS', category: 'Frontend' },
  { value: 'Sass', label: 'Sass', category: 'Frontend' },
  { value: 'Less', label: 'Less', category: 'Frontend' },
  { value: 'Tailwind CSS', label: 'Tailwind CSS', category: 'Frontend' },
  { value: 'Bootstrap', label: 'Bootstrap', category: 'Frontend' },
  { value: 'Material-UI', label: 'Material-UI', category: 'Frontend' },
  { value: 'Ant Design', label: 'Ant Design', category: 'Frontend' },
  { value: 'Chakra UI', label: 'Chakra UI', category: 'Frontend' },
  { value: 'Styled Components', label: 'Styled Components', category: 'Frontend' },
  { value: 'Emotion', label: 'Emotion', category: 'Frontend' },
  { value: 'Webpack', label: 'Webpack', category: 'Frontend' },
  { value: 'Vite', label: 'Vite', category: 'Frontend' },
  { value: 'Parcel', label: 'Parcel', category: 'Frontend' },
  { value: 'Rollup', label: 'Rollup', category: 'Frontend' },
  { value: 'Babel', label: 'Babel', category: 'Frontend' },
  { value: 'ESLint', label: 'ESLint', category: 'Frontend' },
  { value: 'Prettier', label: 'Prettier', category: 'Frontend' },
  { value: 'Jest', label: 'Jest', category: 'Frontend' },
  { value: 'Cypress', label: 'Cypress', category: 'Frontend' },
  { value: 'Playwright', label: 'Playwright', category: 'Frontend' },
  { value: 'Testing Library', label: 'Testing Library', category: 'Frontend' },

  // Backend Technologies
  { value: 'Node.js', label: 'Node.js', category: 'Backend' },
  { value: 'Express.js', label: 'Express.js', category: 'Backend' },
  { value: 'Fastify', label: 'Fastify', category: 'Backend' },
  { value: 'Koa.js', label: 'Koa.js', category: 'Backend' },
  { value: 'NestJS', label: 'NestJS', category: 'Backend' },
  { value: 'Python', label: 'Python', category: 'Backend' },
  { value: 'Django', label: 'Django', category: 'Backend' },
  { value: 'Flask', label: 'Flask', category: 'Backend' },
  { value: 'FastAPI', label: 'FastAPI', category: 'Backend' },
  { value: 'Java', label: 'Java', category: 'Backend' },
  { value: 'Spring Boot', label: 'Spring Boot', category: 'Backend' },
  { value: 'Spring Framework', label: 'Spring Framework', category: 'Backend' },
  { value: 'C#', label: 'C#', category: 'Backend' },
  { value: '.NET', label: '.NET', category: 'Backend' },
  { value: 'ASP.NET', label: 'ASP.NET', category: 'Backend' },
  { value: 'Go', label: 'Go', category: 'Backend' },
  { value: 'Gin', label: 'Gin', category: 'Backend' },
  { value: 'Echo', label: 'Echo', category: 'Backend' },
  { value: 'Ruby', label: 'Ruby', category: 'Backend' },
  { value: 'Ruby on Rails', label: 'Ruby on Rails', category: 'Backend' },
  { value: 'PHP', label: 'PHP', category: 'Backend' },
  { value: 'Laravel', label: 'Laravel', category: 'Backend' },
  { value: 'Symfony', label: 'Symfony', category: 'Backend' },
  { value: 'Rust', label: 'Rust', category: 'Backend' },
  { value: 'Actix', label: 'Actix', category: 'Backend' },
  { value: 'Rocket', label: 'Rocket', category: 'Backend' },
  { value: 'Kotlin', label: 'Kotlin', category: 'Backend' },
  { value: 'Scala', label: 'Scala', category: 'Backend' },
  { value: 'Elixir', label: 'Elixir', category: 'Backend' },
  { value: 'Phoenix', label: 'Phoenix', category: 'Backend' },
  { value: 'Clojure', label: 'Clojure', category: 'Backend' },
  { value: 'Haskell', label: 'Haskell', category: 'Backend' },
  { value: 'F#', label: 'F#', category: 'Backend' },

  // Databases
  { value: 'PostgreSQL', label: 'PostgreSQL', category: 'Database' },
  { value: 'MySQL', label: 'MySQL', category: 'Database' },
  { value: 'MongoDB', label: 'MongoDB', category: 'Database' },
  { value: 'Redis', label: 'Redis', category: 'Database' },
  { value: 'Elasticsearch', label: 'Elasticsearch', category: 'Database' },
  { value: 'Cassandra', label: 'Cassandra', category: 'Database' },
  { value: 'DynamoDB', label: 'DynamoDB', category: 'Database' },
  { value: 'Oracle', label: 'Oracle', category: 'Database' },
  { value: 'SQL Server', label: 'SQL Server', category: 'Database' },
  { value: 'Neo4j', label: 'Neo4j', category: 'Database' },
  { value: 'InfluxDB', label: 'InfluxDB', category: 'Database' },
  { value: 'CouchDB', label: 'CouchDB', category: 'Database' },
  { value: 'RethinkDB', label: 'RethinkDB', category: 'Database' },

  // Cloud & DevOps
  { value: 'AWS', label: 'Amazon Web Services', category: 'Cloud' },
  { value: 'Azure', label: 'Microsoft Azure', category: 'Cloud' },
  { value: 'GCP', label: 'Google Cloud Platform', category: 'Cloud' },
  { value: 'Docker', label: 'Docker', category: 'DevOps' },
  { value: 'Kubernetes', label: 'Kubernetes', category: 'DevOps' },
  { value: 'Terraform', label: 'Terraform', category: 'DevOps' },
  { value: 'Ansible', label: 'Ansible', category: 'DevOps' },
  { value: 'Jenkins', label: 'Jenkins', category: 'DevOps' },
  { value: 'GitLab CI', label: 'GitLab CI', category: 'DevOps' },
  { value: 'GitHub Actions', label: 'GitHub Actions', category: 'DevOps' },
  { value: 'CircleCI', label: 'CircleCI', category: 'DevOps' },
  { value: 'Travis CI', label: 'Travis CI', category: 'DevOps' },
  { value: 'Vagrant', label: 'Vagrant', category: 'DevOps' },
  { value: 'Packer', label: 'Packer', category: 'DevOps' },
  { value: 'Consul', label: 'Consul', category: 'DevOps' },
  { value: 'Vault', label: 'Vault', category: 'DevOps' },
  { value: 'Prometheus', label: 'Prometheus', category: 'DevOps' },
  { value: 'Grafana', label: 'Grafana', category: 'DevOps' },
  { value: 'ELK Stack', label: 'ELK Stack', category: 'DevOps' },
  { value: 'Splunk', label: 'Splunk', category: 'DevOps' },

  // Mobile Development
  { value: 'React Native', label: 'React Native', category: 'Mobile' },
  { value: 'Flutter', label: 'Flutter', category: 'Mobile' },
  { value: 'Xamarin', label: 'Xamarin', category: 'Mobile' },
  { value: 'Ionic', label: 'Ionic', category: 'Mobile' },
  { value: 'Cordova', label: 'Cordova', category: 'Mobile' },
  { value: 'PhoneGap', label: 'PhoneGap', category: 'Mobile' },
  { value: 'Swift', label: 'Swift', category: 'Mobile' },
  { value: 'Kotlin (Android)', label: 'Kotlin (Android)', category: 'Mobile' },
  { value: 'Java (Android)', label: 'Java (Android)', category: 'Mobile' },
  { value: 'Objective-C', label: 'Objective-C', category: 'Mobile' },

  // Data Science & ML
  { value: 'TensorFlow', label: 'TensorFlow', category: 'ML' },
  { value: 'PyTorch', label: 'PyTorch', category: 'ML' },
  { value: 'Scikit-learn', label: 'Scikit-learn', category: 'ML' },
  { value: 'Pandas', label: 'Pandas', category: 'Data Science' },
  { value: 'NumPy', label: 'NumPy', category: 'Data Science' },
  { value: 'Matplotlib', label: 'Matplotlib', category: 'Data Science' },
  { value: 'Seaborn', label: 'Seaborn', category: 'Data Science' },
  { value: 'Plotly', label: 'Plotly', category: 'Data Science' },
  { value: 'Jupyter', label: 'Jupyter', category: 'Data Science' },
  { value: 'Apache Spark', label: 'Apache Spark', category: 'Data Science' },
  { value: 'Hadoop', label: 'Hadoop', category: 'Data Science' },
  { value: 'Kafka', label: 'Kafka', category: 'Data Science' },
  { value: 'Airflow', label: 'Airflow', category: 'Data Science' },
  { value: 'dbt', label: 'dbt', category: 'Data Science' },
  { value: 'Snowflake', label: 'Snowflake', category: 'Data Science' },
  { value: 'BigQuery', label: 'BigQuery', category: 'Data Science' },
  { value: 'Redshift', label: 'Redshift', category: 'Data Science' },

  // Blockchain & Web3
  { value: 'Solidity', label: 'Solidity', category: 'Blockchain' },
  { value: 'Web3.js', label: 'Web3.js', category: 'Blockchain' },
  { value: 'Ethers.js', label: 'Ethers.js', category: 'Blockchain' },
  { value: 'Hardhat', label: 'Hardhat', category: 'Blockchain' },
  { value: 'Truffle', label: 'Truffle', category: 'Blockchain' },
  { value: 'Foundry', label: 'Foundry', category: 'Blockchain' },
  { value: 'IPFS', label: 'IPFS', category: 'Blockchain' },
  { value: 'Ethereum', label: 'Ethereum', category: 'Blockchain' },
  { value: 'Polygon', label: 'Polygon', category: 'Blockchain' },
  { value: 'Solana', label: 'Solana', category: 'Blockchain' },
  { value: 'Cardano', label: 'Cardano', category: 'Blockchain' },
  { value: 'Polkadot', label: 'Polkadot', category: 'Blockchain' },

  // Game Development
  { value: 'Unity', label: 'Unity', category: 'Game Dev' },
  { value: 'Unreal Engine', label: 'Unreal Engine', category: 'Game Dev' },
  { value: 'Godot', label: 'Godot', category: 'Game Dev' },
  { value: 'CryEngine', label: 'CryEngine', category: 'Game Dev' },
  { value: 'Blender', label: 'Blender', category: 'Game Dev' },
  { value: 'Maya', label: 'Maya', category: 'Game Dev' },
  { value: '3ds Max', label: '3ds Max', category: 'Game Dev' },
  { value: 'C# (Unity)', label: 'C# (Unity)', category: 'Game Dev' },
  { value: 'C++ (Unreal)', label: 'C++ (Unreal)', category: 'Game Dev' },
  { value: 'Blueprints', label: 'Blueprints', category: 'Game Dev' },

  // Security
  { value: 'OWASP', label: 'OWASP', category: 'Security' },
  { value: 'Burp Suite', label: 'Burp Suite', category: 'Security' },
  { value: 'Nmap', label: 'Nmap', category: 'Security' },
  { value: 'Metasploit', label: 'Metasploit', category: 'Security' },
  { value: 'Wireshark', label: 'Wireshark', category: 'Security' },
  { value: 'Nessus', label: 'Nessus', category: 'Security' },
  { value: 'OpenVAS', label: 'OpenVAS', category: 'Security' },
  { value: 'Kali Linux', label: 'Kali Linux', category: 'Security' },
  { value: 'Penetration Testing', label: 'Penetration Testing', category: 'Security' },
  { value: 'Vulnerability Assessment', label: 'Vulnerability Assessment', category: 'Security' },

  // Computer Science Fundamentals
  { value: 'OOPS', label: 'OOPS (Object-Oriented Programming)', category: 'Computer Science' },
  { value: 'DBMS', label: 'DBMS (Database Management System)', category: 'Computer Science' },
  { value: 'Computer Networks', label: 'Computer Networks', category: 'Computer Science' },
  { value: 'Operating System', label: 'Operating System', category: 'Computer Science' },
];

// Default topics for new interviews - empty by default
export const DEFAULT_TOPICS: TopicItem[] = [];

// Topics available for machine coding questions (each selection is an individual question)
export const MACHINE_CODING_TOPICS: { value: string; label: string; category?: string }[] = [
  // Frontend / JS
  { value: 'React', label: 'React', category: 'Frontend' },
  { value: 'JavaScript', label: 'JavaScript', category: 'Frontend' },
  { value: 'TypeScript', label: 'TypeScript', category: 'Frontend' },

  // DSA topics (exact database names)
  { value: 'Array', label: 'Array', category: 'DSA' },
  { value: 'Backtracking', label: 'Backtracking', category: 'DSA' },
  { value: 'Binary Search', label: 'Binary Search', category: 'DSA' },
  { value: 'Bit Manipulation', label: 'Bit Manipulation', category: 'DSA' },
  { value: 'Breadth-First Search', label: 'Breadth-First Search', category: 'DSA' },
  { value: 'Concurrency', label: 'Concurrency', category: 'DSA' },
  { value: 'Database', label: 'Database', category: 'DSA' },
  { value: 'Depth-First Search', label: 'Depth-First Search', category: 'DSA' },
  { value: 'Design', label: 'Design', category: 'DSA' },
  { value: 'Divide and Conquer', label: 'Divide and Conquer', category: 'DSA' },
  { value: 'Dynamic Programming', label: 'Dynamic Programming', category: 'DSA' },
  { value: 'Enumeration', label: 'Enumeration', category: 'DSA' },
  { value: 'General', label: 'General', category: 'DSA' },
  { value: 'Graph', label: 'Graph', category: 'DSA' },
  { value: 'Greedy', label: 'Greedy', category: 'DSA' },
  { value: 'Hash Table', label: 'Hash Table', category: 'DSA' },
  { value: 'Linked List', label: 'Linked List', category: 'DSA' },
  { value: 'Math', label: 'Math', category: 'DSA' },
  { value: 'Shell', label: 'Shell', category: 'DSA' },
  { value: 'Sorting', label: 'Sorting', category: 'DSA' },
  { value: 'Stack', label: 'Stack', category: 'DSA' },
  { value: 'String', label: 'String', category: 'DSA' },
  { value: 'Tree', label: 'Tree', category: 'DSA' },
  { value: 'Trie', label: 'Trie', category: 'DSA' },
  { value: 'Two Pointers', label: 'Two Pointers', category: 'DSA' },
  { value: 'Union Find', label: 'Union Find', category: 'DSA' },
];
